name ="example2"
depends = ["core9,https://github.com/Jumpscale/core9/tree/development",
    "lib9,https://github.com/Jumpscale/lib9/tree/development"]

template = "https://github.com/Jumpscale/docgenerator/tree/master/templates/docsify"

baseURL = "/"

doc_add_meta = false

site_name = 'a site name'
disqus = 'a-disqus-name'
